# Generated by Django 4.2.8 on 2023-12-17 22:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'administardor'), (2, 'cliente'), (3, 'dueñorecinto')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(db_column='puntos_usuario', default=0.0)),
                ('telefono', models.CharField(max_length=9)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dueñorecinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador_partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganar', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('F', 'Completo'), ('A', 'Disponible')], default='A', max_length=1)),
                ('tipo', models.CharField(choices=[('Pr', 'Privada'), ('Pu', 'Pública')], max_length=2)),
                ('estilo', models.CharField(choices=[('5', 'Fútbol sala'), ('7', 'Fútbol 7'), ('11', 'Fútbol 11')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion_partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_numerica', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha_votacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacion_usuario', to='appFutbol.cliente')),
                ('partido_votado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacion_partido', to='appFutbol.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField(verbose_name='Goles local')),
                ('goles_visitante', models.IntegerField(verbose_name='Goles visitante')),
                ('resultado_partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_partido', to='appFutbol.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('ubicacion', models.TextField()),
                ('telefono', models.CharField(max_length=9)),
                ('dueño_recinto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.dueñorecinto')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('descuento', models.IntegerField()),
                ('fecha_promocion', models.DateField(default=django.utils.timezone.now)),
                ('miusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creador_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_post', to='appFutbol.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='campo_reservado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campo_reservadoo', to='appFutbol.recinto'),
        ),
        migrations.AddField(
            model_name='partido',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_partido', to='appFutbol.cliente'),
        ),
        migrations.AddField(
            model_name='partido',
            name='usuarios_jugadores',
            field=models.ManyToManyField(related_name='jugadores_partido', through='appFutbol.Jugador_partido', to='appFutbol.cliente'),
        ),
        migrations.AddField(
            model_name='jugador_partido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.partido'),
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('posicion', models.CharField(choices=[('GOA', 'Portero'), ('DEF', 'Defensa'), ('MID', 'Centrocampista'), ('STR', 'Delantero')], max_length=3)),
                ('ubicacion', models.TextField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to='appFutbol.cliente')),
                ('partidos_jugados', models.ManyToManyField(to='appFutbol.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('banco', models.CharField(choices=[('CA', 'Caixa'), ('BB', 'BBVA'), ('UN', 'Unicaja'), ('IN', 'ING')], max_length=2)),
                ('titular_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.cliente')),
            ],
        ),
    ]
